[package]
name = "javy-core"
version = "0.1.0"
authors = ["Saúl Cabrera <saulecabrera@gmail.com>"]
edition = "2018"

[[bin]]
name = "javy_core"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
quickjs-wasm-rs = { path = "../quickjs-wasm-rs", features = ["json"] }
quickjs-wasm-sys = { path = "../quickjs-wasm-sys"}
wee_alloc = "0.4.5"
once_cell = "1.4.0"
lazy_static = "1.4.0"
